name: CI
on:
  push:
    branches: ['main']
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Build
        env:
          NEXT_PUBLIC_COMMIT_ID: $(git rev-parse --short ${{ github.sha }})
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://petebeegle-com/env/prod/.serverless .serverless --delete
      - name: Deploy
        run: npx serverless
      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://petebeegle-com/env/prod/.serverless --delete
